
spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api-docs

---

server:
  port: 8081
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://host.docker.internal:3306/tutorial
    password: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
welocme:
  message: Welcome namaste java -dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: qa
  datasource:
    username: root
    url: jdbc:mysql://host.docker.internal:3306/tutorial
    password: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
welocme:
  message: Welcome namaste java -qa

---

spring:
  profiles: prod
  datasource:
    username: root
    url: jdbc:mysql://host.docker.internal:3306/tutorial
    password: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
welocme:
  message: Welcome namaste java - prod